[mgr]
prepend_keymap = [
{
        on = ["m","p"],
run = '''shell --block --
	PLIST=/tmp/yazi-playlist.m3u
	fd -a --type f \
		-e mp4 -e mkv -e avi -e mov -e webm \
		-e mp3 -e flac -e wav -e m4a -e ogg -e opus > "$PLIST"
	if [ -s "$PLIST" ]; then
		mpv --playlist="$PLIST"
	else
		echo "No media files found." >&2
	fi
	rm -f "$PLIST"
''',
        desc = "play all media in cwd with mpv"
    },
    { on = "y", run = [
        'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list',
        "yank",
    ]},
    { on = ["M","l"], run = "plugin mount", desc = "挂载本地硬盘"},
    { on = ["M","m",], run = "plugin gvfs -- select-then-mount --jump", desc = "选择设备并挂载并跳转" },
    { on = ["M","R",], run = "plugin gvfs -- remount-current-cwd-device", desc = "重新挂载当前目录的设备" },
    { on = ["M","u",], run = "plugin gvfs -- select-then-unmount --eject", desc = "卸载并弹出设备" },
    { on = ["M","U",], run = "plugin gvfs -- select-then-unmount --eject --force", desc = "强制卸载并弹出设备" },
    { on = ["M","a",], run = "plugin gvfs -- add-mount", desc = "添加挂载 URI" },
    { on = ["M","e",], run = "plugin gvfs -- edit-mount", desc = "编辑挂载 URI" },
    { on = ["M","r",], run = "plugin gvfs -- remove-mount", desc = "移除挂载 URI" },
    { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device --automount", desc = "跳转到选定的设备挂载点" },
   
    {on = "<C-t>", run = "tab_create --current", desc = "create new tab"},
    { on = [ "t", "t", "k" ], run = "plugin simple-tag -- toggle-tag", desc = "Toggle a tag (press any key)" },
    { on = [ "t", "a", "k" ], run = "plugin simple-tag -- add-tag", desc = "Add a tag (press any key)" },
    { on = [ "t", "d", "k" ], run = "plugin simple-tag -- remove-tag", desc = "Remove a tag (press any key)" },
    { on = [ "t", "e" ], run = "plugin simple-tag -- edit-tag ", desc = "Edit tag(s) (input box)" },
    { on = [ "t", "f" ], run = "plugin simple-tag -- filter", desc = "Filter files/folders by a tag (press any key)" },
]
