set dotenv-load

sync-clash-rules: replace-config
  @rsync -r clash/ openwrt:utils/caddy/assets/
  @rm clash/config.yaml

replace-config:
  @sed -e "s|\$baiyueguang|${BAIYUEGUANG}|g" -e "s|\$sanyueqi|${SANYUEQI}|g" -e "s|\$enet|${ENET}|g" clash/config.tp.yaml > clash/config.yaml

update-clash-meta-ui:
  @xh POST http://192.168.32.100:9090/upgrade/ui
