set dotenv-load

host := "http://192.168.32.100:9090"

rsync-default-option := "-zar " + if os() == "windows" { '-e D:/scoop/apps/cwrsync/current/bin/ssh.exe' } else { "" }


sync-clash-rules: replace-config
  @rsync {{rsync-default-option}} clash/ openwrt:utils/searxng-docker/assets/
  @echo "更新规则"
  @xh -q PUT {{host}}/providers/rules/custom-proxy
  @rm clash/config.yaml

replace-config:
  @sed -e "s|\$baiyueguang|${BAIYUEGUANG}|g" -e "s|\$sanyueqi|${SANYUEQI}|g" -e "s|\$enet|${ENET}|g" clash/config.tp.yaml > clash/config.yaml

update-clash-meta-ui:
  @xh POST {{host}}/upgrade/ui
  
test:
  @echo {{join("d:/scoop","apps")}}
