[tools]
node = "24.16.0"
go = "latest"
usage = "latest"
golangci-lint = "latest"
biome = "latest"
rust-analyzer = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"npm:@fission-ai/openspec" = "latest"
buf = "latest"
bun = "latest"
"npm:@tobilu/qmd" = "latest"
"go:github.com/Yakitrak/notesmd-cli" = "latest"
"aqua:go-task/task" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"npm:mcporter" = "latest"
"npm:@jackwener/opencli" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"

[tools."github:pnpm/pnpm"]
version = "latest"
asset_pattern = "pnpm-linux-x64.tar.gz"

[settings]
legacy_version_file = true
not_found_auto_install = true
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
idiomatic_version_file_enable_tools = []

[settings.python]
uv_venv_auto = "source"

[settings.npm]
package_manager = "npm"

[env]
_.file = [
    '~/.envs/third-party.toml',
    '~/.envs/vpn.toml',
    { path = "~/.envs/ai-api-key.json", redact = true }
]
