[tools]
node = "latest"
go = "latest"
usage = "latest"
pnpm = "latest"
golangci-lint = "latest"
biome = "latest"
rust-analyzer = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"npm:@fission-ai/openspec" = "latest"
buf = "latest"
bun = "latest"
"npm:node-gyp" = "latest"
"npm:@tobilu/qmd" = "latest"
"go:github.com/Yakitrak/notesmd-cli" = "latest"
"npm:@jackwener/opencli" = "latest"

[settings]
legacy_version_file = true
not_found_auto_install = true
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
idiomatic_version_file_enable_tools = []

[settings.python]
uv_venv_auto = true

[settings.npm]
package_manager = "bun"

[env]
_.file = [
    "~/.env.json"
]
