[tools]
node = "latest"
go = "latest"
usage = "latest"
python = "latest"
pnpm = "latest"
golangci-lint = "latest"
biome = "latest"

[settings]
legacy_version_file = true
not_found_auto_install = true
python_venv_auto_create = true
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
idiomatic_version_file_enable_tools = []
