[tools]
node = "23.9.0"
go = "1.24.0"
usage = "latest"
python = "latest"
pnpm = "10.6.2"
golangci-lint = "latest"
biome = "1.9.4"

[settings]
legacy_version_file = true
not_found_auto_install = true
python_venv_auto_create = true
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
go_set_gobin = true
